[workspace]
members = [
    "serde_with",
    "serde_with_macros",
    "serde_with_test",
]
resolver = "2"

[workspace.metadata.release]
consolidate-commits = true
publish = false
push = false
shared-version = true
sign-tag = true
tag = false

[patch.crates-io]
darling = { git = "https://github.com/jonasbb/darling", branch = "prepare-syn-2" }
# darling = { path = "../darling" }
