[workspace]
members = [
    "serde_with",
    "serde_with_macros",
    "serde_with_test",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/jonasbb/serde_with/"
rust-version = "1.64"
version = "3.3.0"

[workspace.metadata.release]
consolidate-commits = true
pre-release-commit-message = "Bump version to v{{version}}"
publish = false
push = false
shared-version = true
sign-tag = true
tag = false
